# Generated by Django 4.0.2 on 2022-09-20 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlesection',
            options={'verbose_name': 'Раздел статьи', 'verbose_name_plural': 'Разделы статей'},
        ),
        migrations.AlterField(
            model_name='articlesection',
            name='articles',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scope', to='articles.article', verbose_name='Статья'),
        ),
        migrations.AlterField(
            model_name='articlesection',
            name='sections',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scope', to='articles.section', verbose_name='Раздел'),
        ),
    ]
