# Generated by Django 4.0.2 on 2022-09-20 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_alter_articlesection_articles_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlesection',
            options={'verbose_name': 'Тематика статьи', 'verbose_name_plural': 'Тематики статей'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'verbose_name': 'Тематика', 'verbose_name_plural': 'Тематики'},
        ),
        migrations.AlterField(
            model_name='articlesection',
            name='sections',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scopes', to='articles.section', verbose_name='Тематика'),
        ),
        migrations.AlterField(
            model_name='section',
            name='section_name',
            field=models.CharField(max_length=100, verbose_name='Тематика'),
        ),
    ]
