# Generated by Django 4.0.2 on 2022-09-20 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_rename_articles_articlesection_article_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlesection',
            old_name='section',
            new_name='tag',
        ),
    ]
