# Generated by Django 4.0.2 on 2022-10-04 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_remove_student_teacher_student_teachers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='teachers',
            field=models.ManyToManyField(related_name='student', to='school.Teacher', verbose_name='учителя'),
        ),
    ]
