# Generated by Django 4.0.2 on 2022-09-16 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=250, verbose_name='Название')),
                ('price', models.CharField(db_index=True, max_length=10, verbose_name='Цена')),
                ('image', models.ImageField(db_index=True, upload_to='', verbose_name='Изображение')),
                ('release_date', models.DateField(db_index=True, max_length=50, verbose_name='Дата выхода')),
                ('lte_exists', models.BooleanField(verbose_name='Поддержка LTE')),
                ('slug', models.SlugField(max_length=250, unique=True, verbose_name='URL')),
            ],
        ),
    ]
